### PR TITLE
Fix pad length for non UTF-8 characters (fixes #13)

### LINKED ISSUE #13: spongebobsay say incorrectly formats speech bubble when using UTF-8 characters > 1 byte
When using certain Unicode characters, the `spongebobsay` family of functions will incorrectly whitespace pad to form the beech bubble. 

To reproduce:
``` r

library(spongebob)
foo <- paste(
    paste0("pokémon", paste(rep(".", 25), collapse = ""))
    , paste0("pokemon", paste(rep(".", 30), collapse = ""))
)
cat(spongebobsay(foo))
#>  --------------------------------------- 
#> | poKémOn.........................     |
#> | pokEMOn.............................. |
#>  --------------------------------------- 
#>   \\
#>    \\    *
#>           *
#>      ----//-------
#>      \..C/--..--/ \   `A
#>       (@ )  ( @) \  \// |w
#>        \          \  \---/
#>         HGGGGGGG    \    /`
#>         V `---------`--'
#>             <<    <<
#>            ###   ###
```
<sup>Created on 2019-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The problem is because we are using `sprintf` under the hood [here](https://github.com/jayqi/spongebob/blob/master/R/spongebobsay.R#L56-L57). For example, the format code `%-35s` says to print a string and then pad with whitespace on the right to have fill fixed width of 35. 

Unfortunately, `sprintf` documentation says:
> Field widths and precisions of `%s` conversions are interpreted as bytes, not characters, as described in the C standard.

Which is also what is found in the [POSIX standard](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap05.html#tag_05).

This means that any UTF-8 character that is represented by more than 1 byte will have its width incorrectly counted by `sprintf`. 

We'll need an alternative way to pad strings with whitespace that counts characters rather than bytes, possibly a custom function. 

(Note: for a good primer on character encodings, read [Joel Spolsky's seminal article](https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/).)

### PR DESCRIPTION
**Pull request by wdearden**
Fixes #13 

```
> library(spongebob)
> foo <- paste(
+     paste0("pokémon", paste(rep(".", 25), collapse = ""))
+     , paste0("pokemon", paste(rep(".", 30), collapse = ""))
+ )
> spongebobsay(foo)
 --------------------------------------- 
| pOkÉmON.........................      |
| pOkEMon.............................. |
 --------------------------------------- 
  \\
   \\    *
          *
     ----//-------
     \..C/--..--/ \   `A
      (@ )  ( @) \  \// |w
       \          \  \---/
        HGGGGGGG    \    /`
        V `---------`--'
            <<    <<
           ###   ###
```

### CODE REVIEW

File: R/spongebobsay.R [hunk 1]
```diff
@@ -38,6 +38,20 @@
     return(words[which.max(nchar(words))])
 }
 
+# Takes a vector of characters and pads them with spaces to the same length
+.pad_strings_to_fixed_length <- function(txt, length) {
```
Comment (jayqi) [inline R/spongebobsay.R]: I don't like the idea of using `length` as the name of the argument due to collision with the base R `length` function. Can you use something like `lineLength` instead?

**Review by jayqi — CHANGES_REQUESTED** [review]
Thanks so much for the contribution, @wdearden! The function and tests look great overall. Can you please rename the `length` argument? Also, feel free to add yourself to DESCRIPTION as a contributor.

File: R/spongebobsay.R (hunk 1 above)
Comment (wdearden) [reply R/spongebobsay.R]: I agree. Just pushed a new commit.

**Review by jayqi — APPROVED** [review]
LGTM. Thanks @wdearden.
